services:
  dcgm-exporter:
    image: nvcr.io/nvidia/k8s/dcgm-exporter:3.3.5-3.4.0-ubuntu22.04
    deploy: { resources: { reservations: { devices: [ { capabilities: [gpu] } ] } } }
    ports: ["9400:9400"]
  prometheus:
    image: prom/prometheus
    volumes: ["./prometheus.yml:/etc/prometheus/prometheus.yml"]
    ports: ["9090:9090"]
    extra_hosts: ["host.docker.internal:host-gateway"]
  grafana:
    image: grafana/grafana
    ports: ["3000:3000"]
    volumes: ["./grafana:/var/lib/grafana/dashboards"]
    environment: { GF_SECURITY_ADMIN_PASSWORD: admin }
